  - ANDROID_API_LEVEL=25
  - EMULATOR_API_LEVEL=23
  - ANDROID_BUILD_TOOLS_VERSION=26.0.1
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ADB_INSTALL_TIMEOUT=20
  
language: android
android:
  components:
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$ANDROID_API_LEVEL
  - android-$EMULATOR_API_LEVEL
  - add-on
  - extra
  - platform-tools
  - tools
  - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-google_apis-$ANDROID_API_LEVEL
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API_LEVEL
deploy:
    provider: releases
    apikey: $GITHUB_KEY
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true
    on:
      tags: true
script: ./gradlew :app:build
env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
sudo: required

before_script:
    - echo no | android create avd --force -n test -t "android-"$EMULATOR_API_LEVEL --abi $ANDROID_ABI --tag $ANDROID_TAG -s "768x1280"
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

before_install:
  - chmod +x gradlew

