language: android
android:
  components:
  - build-tools-26.0.1
  - android-25
  - android-23
  - add-on
  - extra
  - platform-tools
  - tools
  - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
    - sys-img-armeabi-v7a-android-23
deploy:
    provider: releases
    apikey: $GITHUB_KEY
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true
    on:
      tags: true
script: ./gradlew :app:build
env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
sudo: required

before_script:
    - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a -s "768x1280"
    - emulator -avd test -no-skin -no-audio -no-window &
    - adb wait-for-device
    - adb shell input keyevent 82 &

before_install:
  - chmod +x gradlew

